version: '3'
services:
  app:
    build:
      context: ./app/.
    ports:
      - "80:80"
  postgres:
    build: 
      context: ./postgres/.
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=musicdb
      - POSTGRES_USER=musical
      - POSTGRES_PASSWORD=abcdefg
